# Generated by Django 5.2.4 on 2025-07-31 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('table_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('column_names', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datatable')),
            ],
            options={
                'db_table': 'api_assignment',
            },
        ),
        migrations.CreateModel(
            name='LabelingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=100)),
                ('combined_string_1', models.TextField()),
                ('combined_string_2', models.TextField()),
                ('label', models.CharField(blank=True, choices=[('MATCH', 'Match'), ('UNMATCH', 'Unmatch')], max_length=20, null=True)),
                ('source_table', models.CharField(max_length=255)),
                ('reference_table', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assignment')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labeled_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'table_labeling',
            },
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('source_table', models.CharField(db_index=True, max_length=255)),
                ('reference_table', models.CharField(db_index=True, max_length=255)),
                ('matching_algorithm', models.CharField(choices=[('FAISS', 'FAISS'), ('FUZZY', 'FuzzyWuzzy'), ('TFIDF', 'TF-IDF Cosine'), ('XGBOOST', 'XGBoost'), ('COMBINED', 'Combined Algorithm')], db_index=True, max_length=20)),
                ('matched_data', models.JSONField()),
                ('status', models.CharField(choices=[('MATCH', 'Match'), ('UNMATCH', 'Unmatch'), ('ENRICHED', 'Enriched')], db_index=True, max_length=20)),
                ('confidence_score', models.FloatField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'db_final',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status', 'batch_id'], name='idx_status_batch'), models.Index(fields=['status', 'source_table'], name='idx_status_source'), models.Index(fields=['status', 'reference_table'], name='idx_status_ref'), models.Index(fields=['status', 'matching_algorithm'], name='idx_status_algo'), models.Index(fields=['status', 'confidence_score'], name='idx_status_confidence'), models.Index(fields=['status', '-id'], name='idx_status_id_desc'), models.Index(fields=['batch_id', 'status'], name='idx_batch_status'), models.Index(fields=['source_table', 'reference_table', 'status'], name='idx_tables_status'), models.Index(fields=['matching_algorithm', 'status'], name='idx_algo_status'), models.Index(fields=['created_at', 'status'], name='idx_date_status'), models.Index(fields=['-created_at'], name='idx_created_desc')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('start_index', models.IntegerField(default=0)),
                ('end_index', models.IntegerField(default=0)),
                ('data_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0, help_text='Jumlah data yang sudah dikerjakan')),
                ('is_started', models.BooleanField(default=False, help_text='Apakah employee sudah mulai mengerjakan')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Kapan employee selesai mengerjakan', null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='api.assignment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_employeeassignment',
                'unique_together': {('assignment', 'employee')},
            },
        ),
    ]
