# Generated by Django 5.2.4 on 2025-07-31 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelingdata',
            name='employee',
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_data_count',
            field=models.IntegerField(default=0, help_text='Total data yang di-assign untuk task ini'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labelingdata',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labeling_data', to='api.assignment'),
        ),
        migrations.AlterField(
            model_name='labelingdata',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_labelings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labelingdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='labelingdata',
            name='data_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='labelingdata',
            name='reference_table',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='labelingdata',
            name='source_table',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'created_at'], name='idx_assignment_status_date'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['dataset', 'status'], name='idx_assignment_dataset_status'),
        ),
        migrations.AddIndex(
            model_name='employeeassignment',
            index=models.Index(fields=['employee', 'assignment'], name='idx_emp_assignment'),
        ),
        migrations.AddIndex(
            model_name='employeeassignment',
            index=models.Index(fields=['assignment', 'is_started'], name='idx_assignment_started'),
        ),
        migrations.AddIndex(
            model_name='employeeassignment',
            index=models.Index(fields=['employee', 'completed_at'], name='idx_employee_completed'),
        ),
        migrations.AddIndex(
            model_name='labelingdata',
            index=models.Index(fields=['assignment', 'confirmed_by'], name='idx_assignment_confirmed'),
        ),
        migrations.AddIndex(
            model_name='labelingdata',
            index=models.Index(fields=['assignment', 'label'], name='idx_assignment_label'),
        ),
        migrations.AddIndex(
            model_name='labelingdata',
            index=models.Index(fields=['assignment', 'created_at'], name='idx_assignment_created'),
        ),
        migrations.AddIndex(
            model_name='labelingdata',
            index=models.Index(condition=models.Q(('confirmed_by__isnull', True)), fields=['assignment', 'confirmed_by'], name='idx_labeling_main_query'),
        ),
        migrations.AddIndex(
            model_name='labelingdata',
            index=models.Index(fields=['source_table', 'reference_table'], name='idx_tables'),
        ),
        migrations.AddIndex(
            model_name='labelingdata',
            index=models.Index(fields=['label', 'created_at'], name='idx_label_date'),
        ),
    ]
