# Generated by Django 5.2.4 on 2025-07-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplikat',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='koperasi',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='kopindag',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='kopindagkoperasi',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='snapwangi',
            name='nama',
        ),
        migrations.AddField(
            model_name='duplikat',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='koperasi',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kopindag',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kopindagkoperasi',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapwangi',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
