# Generated by Django 5.2.4 on 2025-07-17 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('column_names', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabelingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=100)),
                ('combined_string_1', models.TextField()),
                ('combined_string_2', models.TextField()),
                ('label', models.CharField(blank=True, choices=[('MATCH', 'Match'), ('UNMATCH', 'Unmatch')], max_length=20, null=True)),
                ('source_table', models.CharField(max_length=255)),
                ('reference_table', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'table_labeling',
            },
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100)),
                ('source_table', models.CharField(max_length=255)),
                ('reference_table', models.CharField(max_length=255)),
                ('matching_algorithm', models.CharField(choices=[('FAISS', 'FAISS'), ('FUZZY', 'FuzzyWuzzy'), ('TFIDF', 'TF-IDF Cosine'), ('XGBOOST', 'XGBoost'), ('COMBINED', 'Combined Algorithm')], max_length=20)),
                ('matched_data', models.JSONField()),
                ('status', models.CharField(choices=[('MATCH', 'Match'), ('UNMATCH', 'Unmatch'), ('ENRICHED', 'Enriched')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'db_final',
            },
        ),
        migrations.DeleteModel(
            name='MatchingData',
        ),
    ]
