# Generated by Django 5.2.4 on 2025-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_duplikat_nama_remove_koperasi_nama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplikat',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='koperasi',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='kopindag',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='kopindagkoperasi',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='snapwangi',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
