# Generated by Django 5.2.4 on 2025-07-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_labelingdata_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Kapan employee selesai mengerjakan', null=True),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='completed_count',
            field=models.IntegerField(default=0, help_text='Jumlah data yang sudah dikerjakan'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='is_started',
            field=models.BooleanField(default=False, help_text='Apakah employee sudah mulai mengerjakan'),
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='api_assignment',
        ),
        migrations.AlterModelTable(
            name='employeeassignment',
            table='api_employeeassignment',
        ),
    ]
