# Generated by Django 5.2.4 on 2025-07-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employeeassignment_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchingresult',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='labelingdata',
            name='assignment',
        ),
        migrations.AlterField(
            model_name='matchingresult',
            name='batch_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='matchingresult',
            name='confidence_score',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='matchingresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='matchingresult',
            name='matching_algorithm',
            field=models.CharField(choices=[('FAISS', 'FAISS'), ('FUZZY', 'FuzzyWuzzy'), ('TFIDF', 'TF-IDF Cosine'), ('XGBOOST', 'XGBoost'), ('COMBINED', 'Combined Algorithm')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='matchingresult',
            name='reference_table',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='matchingresult',
            name='source_table',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='matchingresult',
            name='status',
            field=models.CharField(choices=[('MATCH', 'Match'), ('UNMATCH', 'Unmatch'), ('ENRICHED', 'Enriched')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['status', 'batch_id'], name='idx_status_batch'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['status', 'source_table'], name='idx_status_source'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['status', 'reference_table'], name='idx_status_ref'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['status', 'matching_algorithm'], name='idx_status_algo'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['status', 'confidence_score'], name='idx_status_confidence'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['status', '-id'], name='idx_status_id_desc'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['batch_id', 'status'], name='idx_batch_status'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['source_table', 'reference_table', 'status'], name='idx_tables_status'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['matching_algorithm', 'status'], name='idx_algo_status'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['created_at', 'status'], name='idx_date_status'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['-created_at'], name='idx_created_desc'),
        ),
    ]
